apiVersion: v1
kind: Namespace
metadata:
  name: dev
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cv-demo
data:
    # Override in environment with ingress controller load balancer IP or host
    # E.g http://a8241cbf8317f4c1ab5507fbce9d576c-671821569.us-east-2.elb.amazonaws.com:8080/
    #ALLOWED_ORIGINS: http://a0877996534f34dc69e8c6c27fca7e8f-737672483.us-east-1.elb.amazonaws.com:8080/
    ALLOWED_ORIGINS: http://192.168.1.96:9090
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-demo
  template:
    metadata:
      labels:
        app: cv-demo
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: cv-demo
        image: harness/cv-demo
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 50Mi
        readinessProbe:
          httpGet:
            path: /config
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 2
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
